//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2556.02.18 at 03:59:19 หลังเที่ยง ICT 
//


package th.co.scb.model.customs.mainpayment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import th.co.scb.model.customs.coreschema.SignatureType;
import th.co.scb.model.customs.g1n054.Document;


/**
 * <p>Java class for BankToCustomerGuaranteeDepositNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankToCustomerGuaranteeDepositNotificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:th:singlewindow:xsd:payment:6}DocumentHeader"/>
 *         &lt;element name="PaymentNotification" type="{urn:iso:std:iso:20022:tech:xsd:RTC.G1N.054.01}Document"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankToCustomerGuaranteeDepositNotificationType", propOrder = {
    "documentHeader",
    "paymentNotification",
    "signature"
})
public class BankToCustomerGuaranteeDepositNotificationType {

    @XmlElement(name = "DocumentHeader", required = true)
    protected DocumentHeaderType documentHeader;
    @XmlElement(name = "PaymentNotification", required = true)
    protected Document paymentNotification;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the documentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentHeaderType }
     *     
     */
    public DocumentHeaderType getDocumentHeader() {
        return documentHeader;
    }

    /**
     * Sets the value of the documentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentHeaderType }
     *     
     */
    public void setDocumentHeader(DocumentHeaderType value) {
        this.documentHeader = value;
    }

    /**
     * Gets the value of the paymentNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Document }
     *     
     */
    public Document getPaymentNotification() {
        return paymentNotification;
    }

    /**
     * Sets the value of the paymentNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document }
     *     
     */
    public void setPaymentNotification(Document value) {
        this.paymentNotification = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
