//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2556.02.18 at 03:59:19 หลังเที่ยง ICT 
//


package th.co.scb.model.customs.mainpayment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the th.co.scb.model.customs.mainpayment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BankToCustomerGuaranteeDepositNotification_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "BankToCustomerGuaranteeDepositNotification");
    private final static QName _DocumentHeader_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "DocumentHeader");
    private final static QName _BankToCustomerGuaranteeRefundNotification_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "BankToCustomerGuaranteeRefundNotification");
//    private final static QName _CustomerGuaranteeRefund_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "CustomerGuaranteeRefund");
//    private final static QName _CustomerGuaranteeDepositCancel_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "CustomerGuaranteeDepositCancel");
//    private final static QName _CustomerGuaranteeDeposit_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "CustomerGuaranteeDeposit");
    private final static QName _BankToCustomerGuaranteeDepositCancelNotification_QNAME = new QName("urn:th:singlewindow:xsd:payment:6", "BankToCustomerGuaranteeDepositCancelNotification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: th.co.scb.model.customs.mainpayment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BankToCustomerGuaranteeDepositNotificationType }
     * 
     */
    public BankToCustomerGuaranteeDepositNotificationType createBankToCustomerGuaranteeDepositNotificationType() {
        return new BankToCustomerGuaranteeDepositNotificationType();
    }

    /**
     * Create an instance of {@link BankToCustomerGuaranteeRefundNotificationType }
     * 
     */
    public BankToCustomerGuaranteeRefundNotificationType createBankToCustomerGuaranteeRefundNotificationType() {
        return new BankToCustomerGuaranteeRefundNotificationType();
    }

    /**
     * Create an instance of {@link BankToCustomerGuaranteeDepositCancelNotificationType }
     * 
     */
    public BankToCustomerGuaranteeDepositCancelNotificationType createBankToCustomerGuaranteeDepositCancelNotificationType() {
        return new BankToCustomerGuaranteeDepositCancelNotificationType();
    }

    /**
     * Create an instance of {@link DocumentHeaderType }
     * 
     */
    public DocumentHeaderType createDocumentHeaderType() {
        return new DocumentHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankToCustomerGuaranteeDepositNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:th:singlewindow:xsd:payment:6", name = "BankToCustomerGuaranteeDepositNotification")
    public JAXBElement<BankToCustomerGuaranteeDepositNotificationType> createBankToCustomerGuaranteeDepositNotification(BankToCustomerGuaranteeDepositNotificationType value) {
        return new JAXBElement<BankToCustomerGuaranteeDepositNotificationType>(_BankToCustomerGuaranteeDepositNotification_QNAME, BankToCustomerGuaranteeDepositNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:th:singlewindow:xsd:payment:6", name = "DocumentHeader")
    public JAXBElement<DocumentHeaderType> createDocumentHeader(DocumentHeaderType value) {
        return new JAXBElement<DocumentHeaderType>(_DocumentHeader_QNAME, DocumentHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankToCustomerGuaranteeRefundNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:th:singlewindow:xsd:payment:6", name = "BankToCustomerGuaranteeRefundNotification")
    public JAXBElement<BankToCustomerGuaranteeRefundNotificationType> createBankToCustomerGuaranteeRefundNotification(BankToCustomerGuaranteeRefundNotificationType value) {
        return new JAXBElement<BankToCustomerGuaranteeRefundNotificationType>(_BankToCustomerGuaranteeRefundNotification_QNAME, BankToCustomerGuaranteeRefundNotificationType.class, null, value);
    }

 

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankToCustomerGuaranteeDepositCancelNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:th:singlewindow:xsd:payment:6", name = "BankToCustomerGuaranteeDepositCancelNotification")
    public JAXBElement<BankToCustomerGuaranteeDepositCancelNotificationType> createBankToCustomerGuaranteeDepositCancelNotification(BankToCustomerGuaranteeDepositCancelNotificationType value) {
        return new JAXBElement<BankToCustomerGuaranteeDepositCancelNotificationType>(_BankToCustomerGuaranteeDepositCancelNotification_QNAME, BankToCustomerGuaranteeDepositCancelNotificationType.class, null, value);
    }

}
